services:

  app:
    container_name: app
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
      - ./volumes/media:/media
      - ./volumes/static:/static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:17-alpine
    env_file: .env.dev
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
